/*!
Ice Diagram Pattern Codes v0.3.0 | Software Copyright (c) Shawn Pan
*/
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define(factory);
  } else if (typeof exports === 'object') {
    // Node, CommonJS-like
    module.exports = factory();
  } else {
    // Browser globals (root is window)
    root.DiagramCodes = factory();
  }
}(this, function () {
  'use strict';
  var DiagramCodes = {};

  //Following code is generated by processCodes.py
  //###GENERATED###

  //Return UMD factory result
  return DiagramCodes;
}));